//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBAShipmentDetail
    {
        public int ShipmentDetailID { get; set; }
        public Nullable<int> ShipmentID { get; set; }
        public string AmzShipmentID { get; set; }
        public string Sku { get; set; }
        public string FNSku { get; set; }
        public Nullable<int> QtyShipped { get; set; }
        public Nullable<int> QtyReceived { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string PalletNo { get; set; }
        public Nullable<int> FnskuLabelsPrinted { get; set; }
        public Nullable<int> BoxContentLabelsPrinted { get; set; }
        public Nullable<int> FbaLabelsPrinted { get; set; }
        public Nullable<int> QtyInCase { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string CaseID { get; set; }
        public string ReimbursementID { get; set; }
        public Nullable<int> QtyReimbursed { get; set; }
        public Nullable<System.DateTime> OfficeLastUpdated { get; set; }
        public Nullable<int> OfficeLastUpdatedBy { get; set; }
        public Nullable<decimal> AmtReimbursed { get; set; }
        public Nullable<bool> PrepInfoConfirmed { get; set; }
    }
}
