//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBAShipment
    {
        public int ShipmentID { get; set; }
        public string AmzShipmentID { get; set; }
        public string ShipmentName { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string ShipmentStatus { get; set; }
        public string LabelPrepType { get; set; }
        public string DestFulfmtCenterID { get; set; }
        public string ShipFromAddress1 { get; set; }
        public string ShipFromAddress2 { get; set; }
        public string ShipFromCity { get; set; }
        public string ShipFromState { get; set; }
        public string ShipFromPostalCode { get; set; }
        public string ShipFromDistrictCounty { get; set; }
        public string ShipFromCountry { get; set; }
        public string ShipFromName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string WhseStatus { get; set; }
        public bool AreCasesRequired { get; set; }
        public string BoxContentSource { get; set; }
        public Nullable<int> WhseStatusUpdateBy { get; set; }
        public Nullable<System.DateTime> WhseStatusUpdateDate { get; set; }
        public string OfficeStatus { get; set; }
        public Nullable<int> OfficeStatusUpdateBy { get; set; }
        public Nullable<System.DateTime> OfficeStatusUpdateDate { get; set; }
        public string CaseID { get; set; }
        public string ReimbursmentID { get; set; }
        public Nullable<bool> DoNotSync { get; set; }
        public Nullable<int> ShowWhse { get; set; }
    }
}
