//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsMapping
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string UOM { get; set; }
        public Nullable<int> GR { get; set; }
        public Nullable<int> AP { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<bool> IsMap { get; set; }
    }
}
