//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkuPrepInfo
    {
        public int ID { get; set; }
        public string sku { get; set; }
        public string asin { get; set; }
        public string PrepInstructions { get; set; }
    }
}
