//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string PCName { get; set; }
        public string EnvirmntUserName { get; set; }
        public bool AllowReprice { get; set; }
        public bool AllowReplenish { get; set; }
        public bool AllowSkuSetup { get; set; }
        public bool AllowProducts { get; set; }
        public bool AllowPicksheets { get; set; }
        public bool AllowFbaCalc { get; set; }
        public bool AllowFbaShipments { get; set; }
        public bool AllowReports { get; set; }
        public bool AllowAnalytics { get; set; }
        public bool AllowAppAlerts { get; set; }
        public bool AllowItemForcast { get; set; }
        public bool PromptUpdates { get; set; }
        public bool AllowPrintLabels { get; set; }
        public bool AllowReprintLabels { get; set; }
        public bool AllowSettlements { get; set; }
        public bool AllowCustomerDashboard { get; set; }
        public Nullable<bool> AllowPicking { get; set; }
        public Nullable<int> PinLogin { get; set; }
        public bool AllowListingMirror { get; set; }
        public string Dept { get; set; }
        public string SubDept { get; set; }
        public string Language { get; set; }
        public string AccpacUser { get; set; }
        public string AccpacPassword { get; set; }
        public Nullable<bool> AllowProductSourcing { get; set; }
    }
}
