//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FbaShipment_PcntComplete
    {
        public Nullable<int> ShipmentID { get; set; }
        public decimal pErcentComplete { get; set; }
    }
}
